services:
  - type: web
    name: commerceos-backend
    runtime: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PROD_DB_URL
        sync: false
      - key: PROD_DB_USERNAME
        sync: false
      - key: PROD_DB_PASSWORD
        sync: false
      - key: PROD_REDIS_HOST
        sync: false
      - key: PROD_REDIS_PORT
        value: "6379"
      - key: PROD_REDIS_PASSWORD
        sync: false
      - key: PROD_REDIS_SSL
        value: "true"
      - key: PROD_RABBITMQ_HOST
        sync: false
      - key: PROD_RABBITMQ_PORT
        value: "5672"
      - key: PROD_RABBITMQ_USERNAME
        sync: false
      - key: PROD_RABBITMQ_PASSWORD
        sync: false
      - key: PROD_RABBITMQ_VIRTUAL_HOST
        sync: false
      - key: PROD_RABBITMQ_SSL
        value: "false"
      - key: PROD_JWT_SECRET
        generateValue: true
      - key: PROD_CORS_ALLOWED_ORIGINS
        value: "https://*.vercel.app,http://localhost:*,http://127.0.0.1:*"
